#!/usr/bin/env bash
set -e

# plain docker
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
# Add the package repositories
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable"
sudo apt update
# You may need to pin a specific version with docker-ce=... if nvidia docker is lagging the current docker release
sudo apt install docker-ce docker-compose
sudo docker run hello-world


